version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/setup_AMI.sh
      timeout: 900
  AfterInstall:
    - location: scripts/update_config.sh
      timeout: 900
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 900 
